name: json_compress
description: Json Compression
version: 1.0.2
homepage: https://github.com/ArcaneArts/json_compress
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  jpatch: ^1.0.1
  threshold: ^1.0.3
dev_dependencies:
  test: ^1.22.2
